name: Build

on:
  pull_request:
    branches:
      - 'master'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        pip install -U -r requirements.txt
    - name: Build driver dependencies
      run: |
        cd extensions-doc-builder
        mkdir deps

        echo "Install CTK and minor dependencies"
        pip --quiet install --pre -U chaostoolkit-lib chaostoolkit
        pip --quiet install httplib2 uritemplate pytzdata msrestazure
      
        echo "install all the dependencies for our drivers"
        pip --quiet install -U -r requirements-toolkit.txt

        echo "download all the extensions package to get access to their README and source"
        pip download \
            --no-deps \
            --no-cache-dir \
            --dest deps \
            --no-binary=chaostoolkit-aws,chaostoolkit-azure,chaostoolkit-cloud-foundry,chaostoolkit-google-cloud-platform,chaostoolkit-humio,chaostoolkit-kubernetes,chaostoolkit-prometheus,chaostoolkit-spring,chaostoolkit-toxiproxy,chaostoolkit-opentracing,chaostoolkit-service-fabric,chaostoolkit-istio,chaostoolkit-wiremock,chaostoolkit-gandi,chaostoolkit-dynatrace,chaostoolkit-k6,chaostoolkit-ansible,chaostoolkit-reliably,chaostoolkit-addons,chaostoolkit-grafana,chaostoolkit-slack,chaostoolkit-pixie,chaostoolkit-datadog \
            -r requirements-toolkit.txt

        echo "Installing each extension individually"
        cd deps
        for archive in *.tar.gz;
        do
            tar zxvf "$archive"
            dirname=$(basename $archive .tar.gz)
            cd $dirname
            pip install -e .
            cd ..
        done
        cd ../..
    - name: Build driver pages
      run: |
        cd extensions-doc-builder
        if python ext2md.py; then
            echo "Extension documentation built"
        fi
        cd ..
    - name: Build documentation
      run: |
        mkdir /tmp/site
        cd /tmp/site
        git clone https://$GH_USER_NAME:$GH_USER_PWD@github.com/chaostoolkit/chaostoolkit-documentation.git .
        git checkout gh-pages
        cd -
        git submodule update --init --remote
        mkdocs build --strict -d /tmp/site
        cd ..
